server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: github.com/xiajie1990/springConfig.git #github仓库上面的git仓库名字
          ##搜索目录
          search-paths:
            - springConfig
      #读取分支
      label: master



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka #注册进eureka

