server:
  port: 80

spring:
  application:
    name: feign-order

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka,http://eureka7004.com:7004/eureka
  instance:
    prefer-ip-address: true #访问路径可以显示IP地址

#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000


logging:
    level:
          #feign日志以什么级别监控哪个接口
          com.atguigu.springcloud.service.PaymentFeignService: debug

hystrix:
  metrics:
    enabled: true

feign:
  hystrix:
    enabled: true

